compiler:
    clang

matrix:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"

before_install:
    - eval "${MATRIX_EVAL}"

script:
    mkdir build && cd build && cmake .. && make
